
package firecol;


import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.JOptionPane;
import java.util.*;
import mypack.regdao;
import javax.swing.*;

public class login extends javax.swing.JFrame {

    /** Creates new form login */
    public login() {
        initComponents();
    }
    public boolean validate(String uname,String pword)
{
    boolean validUser = false;
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/firecol","root","admin");
        Statement st=con.createStatement();
        ResultSet rs=st.executeQuery("select email,password from user where email='"+uname+"' and Password='"+pword+"'");
        if(rs.next())
        {
               validUser = true;
        }

    }
    catch(Exception e)
    {
        System.out.println("Exception"+e);
    }


    return validUser;
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel2.setText("Username");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 120, 120, 20);

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\chokkalingam\\Desktop\\images\\proj_button_login.jpg")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(80, 279, 190, 40);

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\chokkalingam\\Desktop\\images\\proj_button_newuser.jpg")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(290, 280, 190, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel3.setText("Password");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 170, 100, 28);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel4.setText("Login Here");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 20, 190, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(200, 120, 210, 20);
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(200, 170, 210, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Documents and Settings\\chokkalingam\\Desktop\\images\\project_label.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-1, 4, 520, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("") || jPasswordField1.getText().equals("")) {

            JOptionPane.showMessageDialog(null,"PLEASE ENTER USERNAME &  PASSWORD","LOGIN",JOptionPane.ERROR_MESSAGE);
        } else if(validate(jTextField1.getText(),jPasswordField1.getText())) {
            //new sender().setVisible(true);
            //JOptionPane.showMessageDialog(null, "Successfull");
             new client1();
            //  new SenderN(jTextField1.getText()).setVisible(true);
            this.setVisible(true);

//            String nodeKey = new keyGenerator().getNodeKey(jTextField1.getText());
//            int i = new regdao().insertNode(jTextField1.getText(),nodeKey);
//
//            if(i>0){
//            JOptionPane.showMessageDialog(this," Your Node ID is "+nodeKey);
//            passport.getPassPortStatus(jTextField1.getText(),nodeKey );
//
//            }

        }


        else {
            JOptionPane.showMessageDialog(null,"INVALID USER","INVALID USER",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Reg().setVisible(true);
        dispose();

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
          try{
        UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");

    }
    catch(Exception e){
        System.out.println("Nimbus isn't available");
    }
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginPage dialog = new LoginPage(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                                new login().setVisible(true);

                //dialog.setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
